=== UBUMonitor/ubumonitor-analytics-api/moodle-java-client/src/main/resources/schema/core/user/getusersbyfield/response/core_user_get_users_by_field.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Response schema for core_enrol_get_users_courses. Returns the list of courses where a user is enrolled in.",
  "type": "array",
  "items": {
    "title": "GetUsersByFieldResponse",
    "type": "object",
    "properties": {
      "country": {
        "nullable": true,
        "description": "Home country code of the user, such as AU or CZ",
        "type": "string"
      },
      "firstname": {
        "nullable": true,
        "description": "The first name(s) of the user",
        "type": "string"
      },
      "auth": {
        "nullable": true,
        "description": "Auth plugins include manual, ldap, etc",
        "type": "string"
      },
      "city": {
        "nullable": true,
        "description": "Home city of the user",
        "type": "string"
      },
      "timezone": {
        "nullable": true,
        "description": "Timezone code such as Australia/Perth, or 99 for default",
        "type": "string"
      },
      "idnumber": {
        "nullable": true,
        "description": "An arbitrary ID code number perhaps from the institution",
        "type": "string"
      },
      "phone2": {
        "nullable": true,
        "description": "Phone 2",
        "type": "string"
      },
      "description": {
        "nullable": true,
        "description": "User profile description",
        "type": "string"
      },
      "firstaccess": {
        "nullable": true,
        "description": "First access to the site (0 if never)",
        "type": "integer",
        "format": "int64"
      },
      "confirmed": {
        "nullable": true,
        "description": "Active user: 1 if confirmed, 0 otherwise",
        "type": "boolean"
      },
      "customfields": {
        "nullable": true,
        "description": "User custom fields (also known as user profile fields)",
        "title": "Custom Fields",
        "type": "array",
        "items": {
          "title": "Custom Field",
          "type": "object",
          "properties": {
            "name": {
              "description": "The name of the custom field",
              "type": "string"
            },
            "type": {
              "description": "The type of the custom field - text field, checkbox...",
              "type": "string"
            },
            "value": {
              "description": "The value of the custom field (as stored in the database)",
              "type": "string"
            },
            "displayvalue": {
              "nullable": true,
              "description": "The value of the custom field for display",
              "type": "string"
            },
            "shortname": {
              "description": "The shortname of the custom field - to be able to build the field class in the code",
              "type": "string"
            }
          },
          "required": [
            "type",
            "value",
            "name",
            "shortname"
          ]
        }
      },
      "phone1": {
        "nullable": true,
        "description": "Phone 1",
        "type": "string"
      },
      "trackforums": {
        "nullable": true,
        "description": "Whether the user is tracking forums",
        "type": "integer"
      },
      "profileimageurlsmall": {
        "description": "User image profile URL - small version",
        "type": "string",
        "format": "uri"
      },
      "institution": {
        "nullable": true,
        "description": "Institution",
        "type": "string"
      },
      "theme": {
        "nullable": true,
        "description": "Theme name such as 'standard', must exist on server",
        "type": "string"
      },
      "id": {
        "description": "ID of the user",
        "type": "integer",
        "format": "int64"
      },
      "department": {
        "nullable": true,
        "description": "Department",
        "type": "string"
      },
      "lang": {
        "nullable": true,
        "description": "Language code such as 'en', must exist on server",
        "type": "string"
      },
      "email": {
        "nullable": true,
        "format": "email",
        "description": "An email address - allow email as root@localhost",
        "type": "string"
      },
      "mailformat": {
        "nullable": true,
        "description": "Mail format code is 0 for plain text, 1 for HTML etc",
        "type": "integer",
        "javaEnums": [
          {
            "name": "MOODLE"
          },
          {
            "name": "HTML"
          },
          {
            "name": "PLAIN"
          },
          {
            "name": "MARKDOWN"
          }
        ],
        "enum": [
          0,
          1,
          2,
          4
        ]
      },
      "preferences": {
        "nullable": true,
        "description": "User preferences",
        "title": "Preferences",
        "type": "array",
        "items": {
          "title": "Preference",
          "type": "object",
          "properties": {
            "name": {
              "description": "The name of the preference",
              "type": "string"
            },
            "value": {
              "description": "The value of the preference",
              "type": "string"
            }
          },
          "required": [
            "name",
            "value"
          ]
        }
      },
      "address": {
        "nullable": true,
        "description": "Postal address",
        "type": "string"
      },
      "suspended": {
        "nullable": true,
        "description": "Suspend user account, either false to enable user login or true to disable it",
        "type": "boolean"
      },
      "lastname": {
        "nullable": true,
        "description": "The family name of the user",
        "type": "string"
      },
      "lastaccess": {
        "nullable": true,
        "description": "Last access to the site (0 if never)",
        "type": "integer",
        "format": "int64"
      },
      "calendartype": {
        "nullable": true,
        "description": "Calendar type such as 'gregorian', must exist on server",
        "type": "string"
      },
      "descriptionformat": {
        "nullable": true,
        "description": "int format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)",
        "type": "integer",
        "javaEnums": [
          {
            "name": "MOODLE"
          },
          {
            "name": "HTML"
          },
          {
            "name": "PLAIN"
          },
          {
            "name": "MARKDOWN"
          }
        ],
        "enum": [
          0,
          1,
          2,
          4
        ]
      },
      "fullname": {
        "description": "The fullname of the user",
        "type": "string"
      },
      "initials": {
        "description": "The initials of the user",
        "type": "string"
      },
      "profileimageurl": {
        "description": "User image profile URL - big version",
        "format": "uri",
        "type": "string"
      },
      "interests": {
        "nullable": true,
        "description": "User interests (separated by commas)",
        "type": "string"
      },
      "username": {
        "nullable": true,
        "description": "The username",
        "type": "string"
      }
    },
    "required": [
      "id",
      "fullname",
      "profileimageurlsmall",
      "profileimageurl"
    ]
  }
}

=== UBUMonitor/ubumonitor-analytics-api/ubumonitor-analytics/src/test/resources/integration/shared/teacher-user-by-field-response.json
[
  {
    "id": 13,
    "username": "teacher",
    "firstname": "Jeffrey",
    "lastname": "Sanders",
    "fullname": "Jeffrey Sanders",
    "initials": "JS",
    "email": "jeffreysanders199@example.com",
    "department": "Senior staff, SE",
    "interests": "travel, gardening, chess, peace, politics, Films, history",
    "firstaccess": 1276064220,
    "lastaccess": 1792955981,
    "auth": "manual",
    "suspended": false,
    "confirmed": true,
    "lang": "en",
    "theme": "",
    "timezone": "99",
    "mailformat": 1,
    "trackforums": 0,
    "description": "<p>The world and its environment has been going through an enormous upheaval particularly in the last few decades. We need to develop thinkers who will be creative, engaged, skilled, informed and thoughtful about the past, present and future interactions of people with each other and their environment. I am passionate about education and enjoy my role at Mount Orange.</p>",
    "descriptionformat": 1,
    "city": "Orange City",
    "country": "AU",
    "profileimageurlsmall": "https://school.moodledemo.net/pluginfile.php/160/user/icon/boost/f2?rev=75854",
    "profileimageurl": "https://school.moodledemo.net/pluginfile.php/160/user/icon/boost/f1?rev=75854",
    "preferences": [
      {
        "name": "assign_filter",
        "value": ""
      },
      {
        "name": "assign_markerfilter",
        "value": ""
      },
      {
        "name": "assign_perpage",
        "value": "20"
      },
      {
        "name": "assign_quickgrading",
        "value": "0"
      },
      {
        "name": "assign_workflowfilter",
        "value": ""
      },
      {
        "name": "assignment_mailinfo",
        "value": "0"
      },
      {
        "name": "auth_forcepasswordchange",
        "value": "0"
      },
      {
        "name": "auth_manual_passwordupdatetime",
        "value": "1777287663"
      },
      {
        "name": "block_myoverview_hidden_course_56",
        "value": "1"
      },
      {
        "name": "block_myoverview_hidden_course_57",
        "value": "1"
      },
      {
        "name": "block_myoverview_hidden_course_6",
        "value": "1"
      },
      {
        "name": "block_myoverview_hidden_course_67",
        "value": "1"
      },
      {
        "name": "block_myoverview_last_tab",
        "value": "timeline"
      },
      {
        "name": "block_myoverview_user_grouping_preference",
        "value": "all"
      },
      {
        "name": "block_myoverview_user_view_preference",
        "value": "cards"
      },
      {
        "name": "block_timeline_user_filter_preference",
        "value": "next6months"
      },
      {
        "name": "block262hidden",
        "value": "0"
      },
      {
        "name": "block263hidden",
        "value": "0"
      },
      {
        "name": "block694hidden",
        "value": "0"
      },
      {
        "name": "calendar_savedflt",
        "value": "13"
      },
      {
        "name": "core_message_migrate_data",
        "value": "1"
      },
      {
        "name": "core_user_welcome",
        "value": "1649737736"
      },
      {
        "name": "course_overview_course_sortorder",
        "value": "62,66,59,64,56,63,35,41,27,58,49,51,40,60,38"
      },
      {
        "name": "course_overview_number_of_courses",
        "value": "7"
      },
      {
        "name": "coursesectionspreferences_59",
        "value": "{\"indexcollapsed\":[459]}"
      },
      {
        "name": "coursesectionspreferences_69",
        "value": "{\"contentcollapsed\":{\"3\":557}}"
      },
      {
        "name": "coursesectionspreferences_73",
        "value": "{\"contentcollapsed\":[]}"
      },
      {
        "name": "coursesectionspreferences_75",
        "value": "{\"contentcollapsed\":[602,601,600,599]}"
      },
      {
        "name": "data_perpage_1",
        "value": "50"
      },
      {
        "name": "docked_block_instance_242",
        "value": "0"
      },
      {
        "name": "docked_block_instance_262",
        "value": "0"
      },
      {
        "name": "docked_block_instance_263",
        "value": "0"
      },
      {
        "name": "docked_block_instance_4",
        "value": "0"
      },
      {
        "name": "docked_block_instance_5",
        "value": "0"
      },
      {
        "name": "docked_block_instance_694",
        "value": "0"
      },
      {
        "name": "docked_block_instance_702",
        "value": "1"
      },
      {
        "name": "docked_block_instance_758",
        "value": "0"
      },
      {
        "name": "docked_block_instance_761",
        "value": "0"
      },
      {
        "name": "docked_block_instance_834",
        "value": "0"
      },
      {
        "name": "docked_block_instance_838",
        "value": "1"
      },
      {
        "name": "docked_block_instance_868",
        "value": "0"
      },
      {
        "name": "drawer-open-block",
        "value": "0"
      },
      {
        "name": "drawer-open-index",
        "value": "0"
      },
      {
        "name": "filepicker_recentlicense",
        "value": "unknown"
      },
      {
        "name": "filepicker_recentrepository",
        "value": "4"
      },
      {
        "name": "flextable_mod_assign_grading",
        "value": "{\"collapse\":[],\"sortby\":{\"timesubmitted\":3,\"userid\":4},\"i_first\":\"\",\"i_last\":\"\",\"textsort\":[]}"
      },
      {
        "name": "forum_displaymode",
        "value": "3"
      },
      {
        "name": "forum_markasreadonnotification",
        "value": "1"
      },
      {
        "name": "forum_useexperimentalui",
        "value": "0"
      },
      {
        "name": "grade_report_showonlyactiveenrol",
        "value": "1"
      },
      {
        "name": "gradingform_guide-showmarkerdesc",
        "value": "1"
      },
      {
        "name": "gradingform_guide-showstudentdesc",
        "value": "1"
      },
      {
        "name": "htmleditor",
        "value": ""
      },
      {
        "name": "ifirst",
        "value": ""
      },
      {
        "name": "ilast",
        "value": ""
      },
      {
        "name": "last_time_enrolments_synced",
        "value": "1792954899"
      },
      {
        "name": "login_failed_count_since_success",
        "value": "0"
      },
      {
        "name": "message_beepnewmessage",
        "value": "0"
      },
      {
        "name": "message_blocknoncontacts",
        "value": "0"
      },
      {
        "name": "message_processor_email_email",
        "value": "jeffreysanders199@example.com"
      },
      {
        "name": "message_provider_enrol_manual_expiry_notification_enabled",
        "value": "email"
      },
      {
        "name": "message_provider_enrol_self_expiry_notification_enabled",
        "value": "email"
      },
      {
        "name": "message_provider_mod_assign_assign_notification_enabled",
        "value": "email"
      },
      {
        "name": "message_provider_mod_feedback_message_enabled",
        "value": "email"
      },
      {
        "name": "message_provider_mod_feedback_submission_enabled",
        "value": "email"
      },
      {
        "name": "message_provider_mod_forum_posts_enabled",
        "value": "email,popup"
      },
      {
        "name": "message_provider_mod_lesson_graded_essay_enabled",
        "value": "email"
      },
      {
        "name": "message_provider_moodle_badgecreatornotice_enabled",
        "value": "email"
      },
      {
        "name": "message_provider_moodle_badgerecipientnotice_enabled",
        "value": "email,popup"
      },
      {
        "name": "message_provider_moodle_courserequestapproved_enabled",
        "value": "email"
      },
      {
        "name": "message_provider_moodle_courserequestrejected_enabled",
        "value": "email"
      },
      {
        "name": "message_provider_moodle_errors_enabled",
        "value": "email,popup"
      },
      {
        "name": "message_provider_moodle_instantmessage_enabled",
        "value": "email,popup"
      },
      {
        "name": "message_provider_moodle_notices_enabled",
        "value": "email,popup"
      },
      {
        "name": "message_provider_tool_messageinbound_invalidrecipienthandler_enabled",
        "value": "email"
      },
      {
        "name": "message_provider_tool_messageinbound_messageprocessingerror_enabled",
        "value": "email"
      },
      {
        "name": "message_provider_tool_messageinbound_messageprocessingsuccess_enabled",
        "value": "email"
      },
      {
        "name": "message_provider_tool_monitor_notification_enabled",
        "value": "popup"
      },
      {
        "name": "mod_imscp_mod_form_showadvanced",
        "value": "1"
      },
      {
        "name": "mod_wiki_mod_form_showadvanced",
        "value": "1"
      },
      {
        "name": "qbank_managecategories_includesubcategories_filter_default",
        "value": "0"
      },
      {
        "name": "qtype_multichoice_answernumbering",
        "value": "none"
      },
      {
        "name": "qtype_multichoice_defaultmark",
        "value": "1"
      },
      {
        "name": "qtype_multichoice_penalty",
        "value": "0.3333333"
      },
      {
        "name": "qtype_multichoice_showstandardinstruction",
        "value": "0"
      },
      {
        "name": "qtype_multichoice_shuffleanswers",
        "value": "1"
      },
      {
        "name": "qtype_multichoice_single",
        "value": "1"
      },
      {
        "name": "qtype_ordering_defaultmark",
        "value": "1"
      },
      {
        "name": "qtype_ordering_gradingtype",
        "value": "0"
      },
      {
        "name": "qtype_ordering_layouttype",
        "value": "1"
      },
      {
        "name": "qtype_ordering_numberingstyle",
        "value": "none"
      },
      {
        "name": "qtype_ordering_penalty",
        "value": "0.3333333"
      },
      {
        "name": "qtype_ordering_selectcount",
        "value": "2"
      },
      {
